### PR TITLE
Auto depend rtype-java

### PR DESCRIPTION
**Pull request by skull-squadron**
`jgem build rtype.gemspec && jgem push rtype-0.6.6-java.gem`

### CODE REVIEW

**Comment by sputnikgugja** [comment]
``` ruby
# rtype.gemspec in your commits
...
if defined?(JRUBY_VERSION)
  s.platform = "java"
  s.add_dependency "rtype-java", Rtype::VERSION
end
...
```

.gemspec runs at gem installation (`gem install ...`) time?
As far as I know, It doesn't?

**Comment by skull-squadron** [comment]
Not so. They also run during gem packaging. This how to create a
multiplatform gem. See another gem I wrote called oui-offline.

**Comment by sputnikgugja** [comment]
oh, I see. I understand your way. but, I apologize to say that I don't use it for a few reasons. One of the reasons, I don't want to force extension dependency.

**Comment by skull-squadron** [comment]
It's a stepping-stone to folding a JRuby and pure ruby gem together as
concurrent-ruby, bson and many others use this pattern. In fact, it's
possible to fold a java native gem into the main gem, where JRuby gets it's
own rtype-X.Y.Z-java.gem while all others get rtype-X.Y.Z.gem. There is no
disadvantage and it saves people effort from going and getting other gems,
documenting it and having to do something else manually. The reason gems
like bson_ext non-dependency "accelerator" gems exist is the lack of
disambiguation for C-extension capabilities in the gemspec API.

**Comment by sputnikgugja** [comment]
okay. I will add it soon. (both rtype and rtype-legacy)

**Pull request closed without merging**
